name: make-puzzle-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: compile check
        uses: docker://amutake/satysfi:0.0.3-dev2019.07.14
        run: satysfi test/test.saty -o test/test.pdf
