name: make-puzzle-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: compile check
        run: docker run --rm -v $(pwd):/home/opam/satysfi amutake/satysfi satysfi /home/runner/work/make-puzzle/make-puzzle/test/test.saty -o /home/runner/work/make-puzzle/make-puzzle/test/test.pdf
